AWSTemplateFormatVersion: "2010-09-09"
Description: "Test deployment of cfn-toolkit"
Parameters:
  LambdaS3Bucket:
    Type: String
    Description: The S3 bucket containing the Lambda package.
  LambdaS3Key:
    Type: String
    Description: The S3 key containing the Lambda package.
  LambdaS3Version:
    Type: String
    Description: The S3 version identifier of the Lambda package to deploy.
  LambdaRoleArn:
    Type: String
    Description: The Role ARN for the Lambda function to assume.
Resources:
  ApiFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaS3Key
        S3ObjectVersion: !Ref LambdaS3Version
      Handler: handler.lambda_handler
      MemorySize: 128
      Role: !GetAtt LambdaApiRole.Arn
      Runtime: python3.6
      Timeout: 10
